FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD data-collector.jar /opt/data-collector/
EXPOSE 8080
WORKDIR /opt/data-collector/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "data-collector.jar"]
