# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:// 172.17.0.1:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
debug: true
logging:
  file: /var/log/application-debug.log
  level:
    root: WARN # the minimum logging level for the application.
    vargovcik.peter.datacollector: INFO # the minimum logging level for the core application code.